//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChamCong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChamCong()
        {
            this.Luongs = new HashSet<Luong>();
        }
    
        public string MaNV { get; set; }
        public Nullable<double> HeSBL { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<System.TimeSpan> GioVao { get; set; }
        public Nullable<System.TimeSpan> GioRa { get; set; }
        public Nullable<System.TimeSpan> ThoiGian { get; set; }
        public Nullable<int> Phep { get; set; }
        public Nullable<int> KhongPhep { get; set; }
        public Nullable<int> SoNgay { get; set; }
        public Nullable<System.TimeSpan> TangCa { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Luong> Luongs { get; set; }
    }
}
