//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhenThuong
    {
        public string MaNV { get; set; }
        public string LyDo { get; set; }
        public string ThangThuong { get; set; }
        public string TienThuong { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
