//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Luong
    {
        public string MaLuong { get; set; }
        public string MaNV { get; set; }
        public Nullable<double> TienThuong { get; set; }
        public Nullable<double> TienPhat { get; set; }
        public Nullable<System.DateTime> NgayNhanLuong { get; set; }
        public Nullable<double> TongTienLuong { get; set; }
    
        public virtual ChamCong ChamCong { get; set; }
    }
}
