//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public string MaNV { get; set; }
        public string HoTen { get; set; }
        public string Diachi { get; set; }
        public int CMND { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public bool GioiTinh { get; set; }
        public string QueQuan { get; set; }
        public int SDT { get; set; }
        public string MaPhongBan { get; set; }
        public string MaTonGiao { get; set; }
        public string MaDanToc { get; set; }
        public int TrinhDo { get; set; }
        public string MaBacLuong { get; set; }
        public string MaChucVuNV { get; set; }
        public string MaHopDong { get; set; }
    
        public virtual ChamCong ChamCong { get; set; }
        public virtual ChucVu ChucVu { get; set; }
        public virtual DanToc DanToc { get; set; }
        public virtual HopDong HopDong { get; set; }
        public virtual KhenThuong KhenThuong { get; set; }
        public virtual KyLuat KyLuat { get; set; }
        public virtual PhongBan PhongBan { get; set; }
        public virtual TonGiao TonGiao { get; set; }
        public virtual ThoiViec ThoiViec { get; set; }
    }
}
