//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [Required(ErrorMessage ="Tài Khoản không được để trống ... !")]
        [DisplayName("Tài Khoản")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "Mật Khẩu không được để trống ... !")]
        [DisplayName("Mật Khẩu")]
        [DataType(DataType.Password)]
        public string PassWord { get; set; }
        [Required(ErrorMessage = "Quyền không được để trống ... !")]
        [DisplayName("Quyền")]
        public string Role { get; set; }
    }
}
